// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPsqPrjwQW4h2jypTtbc_4Ltf07XyBMKM',
    appId: '1:45154033239:web:f7e73550c30ca9847a8d12',
    messagingSenderId: '45154033239',
    projectId: 'ecomm-1cf52',
    authDomain: 'ecomm-1cf52.firebaseapp.com',
    storageBucket: 'ecomm-1cf52.appspot.com',
    measurementId: 'G-8X0C2LTZKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxgDUEHXZSF9CMV7LUm92U9d3-SdU0jtk',
    appId: '1:45154033239:android:2965f3de8e651ffe7a8d12',
    messagingSenderId: '45154033239',
    projectId: 'ecomm-1cf52',
    storageBucket: 'ecomm-1cf52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2n6aN4sjivYtWl6v1NXsJ2-s8ft1HHdc',
    appId: '1:45154033239:ios:8c5f270ad7063fbf7a8d12',
    messagingSenderId: '45154033239',
    projectId: 'ecomm-1cf52',
    storageBucket: 'ecomm-1cf52.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2n6aN4sjivYtWl6v1NXsJ2-s8ft1HHdc',
    appId: '1:45154033239:ios:b4bc4c53b4d9f5f87a8d12',
    messagingSenderId: '45154033239',
    projectId: 'ecomm-1cf52',
    storageBucket: 'ecomm-1cf52.appspot.com',
    iosBundleId: 'com.example.eComm.RunnerTests',
  );
}
